SECTION "Text 1", ROMX

INCLUDE "data/text/english/text_1.asm"

INCLUDE "text/english/ViridianForest.asm"
INCLUDE "text/english/MtMoon1F.asm"
INCLUDE "text/english/MtMoonB1F.asm"
INCLUDE "text/english/MtMoonB2F.asm"
INCLUDE "text/english/SSAnne1F.asm"
INCLUDE "text/english/SSAnne2F.asm"
INCLUDE "text/english/SSAnne3F.asm"
INCLUDE "text/english/SSAnneBow.asm"
INCLUDE "text/english/SSAnneKitchen.asm"
INCLUDE "text/english/SSAnneCaptainsRoom.asm"
INCLUDE "text/english/SSAnne1FRooms.asm"
INCLUDE "text/english/SSAnne2FRooms.asm"
INCLUDE "text/english/SSAnneB1FRooms.asm"
INCLUDE "text/english/VictoryRoad3F.asm"
INCLUDE "text/english/RocketHideoutB1F.asm"
INCLUDE "text/english/RocketHideoutB2F.asm"
INCLUDE "text/english/RocketHideoutB3F.asm"
INCLUDE "text/english/RocketHideoutB4F.asm"
INCLUDE "text/english/RocketHideoutElevator.asm"
INCLUDE "text/english/SilphCo2F.asm"
INCLUDE "text/english/SilphCo3F.asm"
INCLUDE "text/english/SilphCo4F.asm"
INCLUDE "text/english/SilphCo5F.asm"

SECTION "Text 2", ROMX

INCLUDE "text/english/SilphCo5F_2.asm"
INCLUDE "text/english/SilphCo6F.asm"
INCLUDE "text/english/SilphCo7F.asm"
INCLUDE "text/english/SilphCo8F.asm"
INCLUDE "text/english/SilphCo9F.asm"
INCLUDE "text/english/SilphCo10F.asm"
INCLUDE "text/english/SilphCo11F.asm"
INCLUDE "text/english/PokemonMansion2F.asm"
INCLUDE "text/english/PokemonMansion3F.asm"
INCLUDE "text/english/PokemonMansionB1F.asm"
INCLUDE "text/english/SafariZoneEast.asm"
INCLUDE "text/english/SafariZoneNorth.asm"
INCLUDE "text/english/SafariZoneWest.asm"
INCLUDE "text/english/SafariZoneCenter.asm"
INCLUDE "text/english/SafariZoneCenterRestHouse.asm"
INCLUDE "text/english/SafariZoneSecretHouse.asm"
INCLUDE "text/english/SafariZoneWestRestHouse.asm"
INCLUDE "text/english/SafariZoneEastRestHouse.asm"
INCLUDE "text/english/SafariZoneNorthRestHouse.asm"
INCLUDE "text/english/CeruleanCaveB1F.asm"
INCLUDE "text/english/VictoryRoad1F.asm"
INCLUDE "text/english/LancesRoom.asm"
INCLUDE "text/english/HallOfFame.asm"
INCLUDE "text/english/ChampionsRoom.asm"
INCLUDE "text/english/LoreleisRoom.asm"
INCLUDE "text/english/BrunosRoom.asm"
INCLUDE "text/english/AgathasRoom.asm"
INCLUDE "text/english/RockTunnelB1F.asm"


SECTION "Text 3", ROMX

INCLUDE "text/english/RockTunnelB1F_2.asm"
INCLUDE "text/english/SeafoamIslandsB4F.asm"

INCLUDE "data/text/english/text_2.asm"

INCLUDE "text/english/DiglettsCaveRoute2.asm"
INCLUDE "text/english/ViridianForestNorthGate.asm"
INCLUDE "text/english/Route2TradeHouse.asm"
INCLUDE "text/english/Route2Gate.asm"
INCLUDE "text/english/ViridianForestSouthGate.asm"
INCLUDE "text/english/MtMoonPokecenter.asm"
INCLUDE "text/english/SaffronGates.asm"
INCLUDE "text/english/Daycare.asm"

SECTION "Text 4", ROMX

INCLUDE "text/english/Daycare_2.asm"
INCLUDE "text/english/UndergroundPathRoute6.asm"
INCLUDE "text/english/UndergroundPathRoute7.asm"
INCLUDE "text/english/UndergroundPathRoute7Copy.asm"
INCLUDE "text/english/UndergroundPathRoute8.asm"
INCLUDE "text/english/RockTunnelPokecenter.asm"
INCLUDE "text/english/RockTunnel1F.asm"
INCLUDE "text/english/PowerPlant.asm"
INCLUDE "text/english/Route11Gate1F.asm"
INCLUDE "text/english/Route11Gate2F.asm"
INCLUDE "text/english/DiglettsCaveRoute11.asm"
INCLUDE "text/english/Route12Gate1F.asm"
INCLUDE "text/english/Route12Gate2F.asm"
INCLUDE "text/english/Route12SuperRodHouse.asm"
INCLUDE "text/english/Route15Gate1F.asm"
INCLUDE "text/english/Route15Gate2F.asm"
INCLUDE "text/english/Route16Gate1F.asm"
INCLUDE "text/english/Route16Gate2F.asm"
INCLUDE "text/english/Route16FlyHouse.asm"
INCLUDE "text/english/Route18Gate1F.asm"
INCLUDE "text/english/Route18Gate2F.asm"
INCLUDE "text/english/Route22Gate.asm"
INCLUDE "text/english/VictoryRoad2F.asm"
INCLUDE "text/english/BillsHouse.asm"
INCLUDE "text/english/Route1.asm"
INCLUDE "text/english/Route2.asm"
INCLUDE "text/english/Route3.asm"
INCLUDE "text/english/Route4.asm"
INCLUDE "text/english/Route5.asm"
INCLUDE "text/english/Route6.asm"
INCLUDE "text/english/Route7.asm"
INCLUDE "text/english/Route8.asm"
INCLUDE "text/english/Route9.asm"
INCLUDE "text/english/Route10.asm"
INCLUDE "text/english/Route11.asm"

SECTION "Text 5", ROMX

INCLUDE "text/english/Route11_2.asm"
INCLUDE "text/english/Route12.asm"
INCLUDE "text/english/Route13.asm"
INCLUDE "text/english/Route14.asm"
INCLUDE "text/english/Route15.asm"
INCLUDE "text/english/Route16.asm"
INCLUDE "text/english/Route17.asm"
INCLUDE "text/english/Route18.asm"
INCLUDE "text/english/Route19.asm"
INCLUDE "text/english/Route20.asm"
INCLUDE "text/english/Route21.asm"
INCLUDE "text/english/Route22.asm"
INCLUDE "text/english/Route23.asm"
INCLUDE "text/english/Route24.asm"

SECTION "Text 6", ROMX

INCLUDE "text/english/Route24_2.asm"
INCLUDE "text/english/Route25.asm"

INCLUDE "data/text/english/text_3.asm"

INCLUDE "text/english/RedsHouse1F.asm"
INCLUDE "text/english/BluesHouse.asm"
INCLUDE "text/english/OaksLab.asm"
INCLUDE "text/english/pokedex_ratings.asm"
INCLUDE "text/english/ViridianPokecenter.asm"
INCLUDE "text/english/ViridianMart.asm"
INCLUDE "text/english/ViridianSchoolHouse.asm"
INCLUDE "text/english/ViridianNicknameHouse.asm"
INCLUDE "text/english/ViridianGym.asm"
INCLUDE "text/english/Museum1F.asm"
INCLUDE "text/english/Museum2F.asm"
INCLUDE "text/english/PewterGym.asm"

SECTION "Text 7", ROMX

INCLUDE "text/english/PewterGym_2.asm"
INCLUDE "text/english/PewterNidoranHouse.asm"
INCLUDE "text/english/PewterMart.asm"
INCLUDE "text/english/PewterSpeechHouse.asm"
INCLUDE "text/english/PewterPokecenter.asm"
INCLUDE "text/english/CeruleanTrashedHouse.asm"
INCLUDE "text/english/CeruleanTradeHouse.asm"
INCLUDE "text/english/CeruleanPokecenter.asm"
INCLUDE "text/english/CeruleanGym.asm"
INCLUDE "text/english/BikeShop.asm"
INCLUDE "text/english/CeruleanMart.asm"
INCLUDE "text/english/CeruleanBadgeHouse.asm"
INCLUDE "text/english/LavenderPokecenter.asm"
INCLUDE "text/english/PokemonTower1F.asm"
INCLUDE "text/english/PokemonTower2F.asm"
INCLUDE "text/english/PokemonTower3F.asm"
INCLUDE "text/english/PokemonTower4F.asm"
INCLUDE "text/english/PokemonTower5F.asm"
INCLUDE "text/english/PokemonTower6F.asm"
INCLUDE "text/english/PokemonTower7F.asm"
INCLUDE "text/english/MrFujisHouse.asm"
INCLUDE "text/english/LavenderMart.asm"
INCLUDE "text/english/LavenderCuboneHouse.asm"
INCLUDE "text/english/NameRatersHouse.asm"
INCLUDE "text/english/VermilionPokecenter.asm"
INCLUDE "text/english/PokemonFanClub.asm"
INCLUDE "text/english/VermilionMart.asm"
INCLUDE "text/english/VermilionGym.asm"

SECTION "Text 8", ROMX

INCLUDE "text/english/VermilionGym_2.asm"
INCLUDE "text/english/VermilionPidgeyHouse.asm"
INCLUDE "text/english/VermilionDock.asm"
INCLUDE "text/english/VermilionOldRodHouse.asm"
INCLUDE "text/english/CeladonMart1F.asm"
INCLUDE "text/english/CeladonMart2F.asm"
INCLUDE "text/english/CeladonMart3F.asm"
INCLUDE "text/english/CeladonMart4F.asm"
INCLUDE "text/english/CeladonMartRoof.asm"
INCLUDE "text/english/CeladonMansion1F.asm"
INCLUDE "text/english/CeladonMansion2F.asm"
INCLUDE "text/english/CeladonMansion3F.asm"
INCLUDE "text/english/CeladonMansionRoof.asm"
INCLUDE "text/english/CeladonMansionRoofHouse.asm"
INCLUDE "text/english/CeladonPokecenter.asm"
INCLUDE "text/english/CeladonGym.asm"
INCLUDE "text/english/GameCorner.asm"
INCLUDE "text/english/CeladonMart5F.asm"
INCLUDE "text/english/GameCornerPrizeRoom.asm"
INCLUDE "text/english/CeladonDiner.asm"
INCLUDE "text/english/CeladonChiefHouse.asm"
INCLUDE "text/english/CeladonHotel.asm"
INCLUDE "text/english/FuchsiaMart.asm"
INCLUDE "text/english/FuchsiaBillsGrandpasHouse.asm"
INCLUDE "text/english/FuchsiaPokecenter.asm"
INCLUDE "text/english/WardensHouse.asm"
INCLUDE "text/english/SafariZoneGate.asm"
INCLUDE "text/english/FuchsiaGym.asm"

SECTION "Text 9", ROMX

INCLUDE "text/english/FuchsiaGym_2.asm"
INCLUDE "text/english/FuchsiaMeetingRoom.asm"
INCLUDE "text/english/FuchsiaGoodRodHouse.asm"
INCLUDE "text/english/PokemonMansion1F.asm"
INCLUDE "text/english/CinnabarGym.asm"
INCLUDE "text/english/CinnabarLab.asm"
INCLUDE "text/english/CinnabarLabTradeRoom.asm"
INCLUDE "text/english/CinnabarLabMetronomeRoom.asm"
INCLUDE "text/english/CinnabarLabFossilRoom.asm"
INCLUDE "text/english/CinnabarPokecenter.asm"
INCLUDE "text/english/CinnabarMart.asm"
INCLUDE "text/english/IndigoPlateauLobby.asm"
INCLUDE "text/english/CopycatsHouse1F.asm"
INCLUDE "text/english/CopycatsHouse2F.asm"
INCLUDE "text/english/FightingDojo.asm"
INCLUDE "text/english/SaffronGym.asm"
INCLUDE "text/english/SaffronPidgeyHouse.asm"
INCLUDE "text/english/SaffronMart.asm"
INCLUDE "text/english/SilphCo1F.asm"
INCLUDE "text/english/SaffronPokecenter.asm"
INCLUDE "text/english/MrPsychicsHouse.asm"

INCLUDE "data/text/english/text_4.asm"

SECTION "Text 10", ROMX

INCLUDE "data/text/english/text_5.asm"

INCLUDE "text/english/PalletTown.asm"
INCLUDE "text/english/ViridianCity.asm"
INCLUDE "text/english/PewterCity.asm"
INCLUDE "text/english/CeruleanCity.asm"
INCLUDE "text/english/LavenderTown.asm"
INCLUDE "text/english/VermilionCity.asm"
INCLUDE "text/english/CeladonCity.asm"
INCLUDE "text/english/FuchsiaCity.asm"
INCLUDE "text/english/CinnabarIsland.asm"
INCLUDE "text/english/SaffronCity.asm"

INCLUDE "data/text/english/text_6.asm"

SECTION "Text 11", ROMX

INCLUDE "data/text/english/text_7.asm"

SECTION "Pokédex Text", ROMX

INCLUDE "data/text/english/pokedex_text.asm"


SECTION "Move Names", ROMX

INCLUDE "data/text/english/moves.asm"
